version: "3"
services:
  xmas:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - 3000:3000
    environment:
      DB_PATH: /xmas/db.json
      AUTH_USERNAME: test
      AUTH_PASSWORD: test
    volumes:
      - db:/xmas

volumes:
  db: