name: build

on:
  push:
    branches:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          platforms: linux/arm/v7,linux/amd64
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx
        run: |
          docker buildx build \
            --cache-from gvidelio/xmas:latest \
            --platform linux/arm/v7,linux/amd64 \
            --tag "gvidelio/xmas:latest" \
            --tag "gvidelio/xmas:${GITHUB_REF##*/}" \
            --file ./Dockerfile .